### ISSUE TITLE
Create Alexa Skill sample with Go 

### ISSUE THREAD

**Issue by nfuhs** [nfuhs/skill-sample-go-fact#1]
Go port of [https://github.com/alexa/skill-sample-nodejs-fact](https://github.com/alexa/skill-sample-nodejs-fact)

**Comment by josephyi** [comment]
#2 isn't a complete implementation of the facts skill, but should be a good start.

**Comment by nfuhs** [comment]
Thanks @josephyi I merged it.

I currently work  on a quick and dirty port of [https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs) as soon as it is up I will post a new issue here

**Comment by nfuhs** [comment]
Hi @josephyi I would like to know if I add a crude basic CLI to the sample would you test it since you have an aws account?

**Comment by josephyi** [comment]
sure I can test

**Comment by nfuhs** [comment]
Found way to get a free AWS account without credit card , will write the CLI tool when its done I will post here stay tuned fingers crossed.
